### ISSUE TITLE
failing

### ISSUE THREAD

**Issue by meciah101** [IntelSDM/RustDMAESP#6]
![image](https://github.com/user-attachments/assets/36480384-2a62-4950-b98b-61d5a8a386cb)
just stops after this

**Comment by IntelSDM** [comment]
You have to update the offsets as detailed in the update guide.

**Comment by victordark41** [comment]
if you updated it today, why does it still not work?

**Comment by IntelSDM** [comment]
It was not updated Yesterday. Someone posted a pull request which makes the repo seem like it has been updated. I pulled their request so it should work now.

**Comment by michalbreakthru** [comment]
it still doesn't work, the program stops at the moment as in the screenshot above

**Comment by meciah101** [comment]
even after updating still just closes

**Comment by nobans** [comment]
uint64_t occlusioncullingclass = 230312600;
uint64_t instance = TargetProcess.Read<uint64_t>(staticclass + 0x248);
